### ISSUE TITLE
Sample usage

### ISSUE THREAD

**Issue by robertio** [RetepRelleum/uPyVoip#5]
Please give me some hint how to use.
I have a fritz.box as voip server but based on other Server example i can figure out how to use.

**Comment by RetepRelleum** [comment]
> Please give me some hint how to use. I have a fritz.box as voip server but based on other Server example i can figure out how to use.

Hello  Robert IO 

have a look at 
https://www.espressif.com/en/news/ESP32_VoIP

I think uPython is not a god idea. I like c wirh  esp-idf 

Best regard Peter
